import Head from "next/head";
import Hero from "../components/Hero";
import ProductList from "../components/ProductList";
import { getProductsInCollection } from "../lib/shopify";

export default function Home({ products }) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div>
        <Hero />
        <ProductList products={products} />
      </div>
    </>
  );
}

export async function getStaticProps(context) {
  const products = await getProductsInCollection();

  return {
    props: {
      products,
    },
  };
}
